name: Deploy Static Website to Azure Web App - PREPARCER

on:
  push:
    branches:
      - main  # Déclenchement sur push dans la branche main
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'PREPARCER'  # Nom de votre application sur Azure
        slot-name: 'production'  # Slot par défaut
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Profil de publication Azure
        package: .  # Déploie tous les fichiers du dépôt
