name: Deploy Static Website to Azure Web App - PREPARCER

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: Azure/webapps-deploy@v2  # Ensure you are using the latest version
      with:
        app-name: 'PREPARCER'  # Replace with your Azure Web App name
        slot-name: 'production'  # Replace with your deployment slot (default is production)
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use the publish profile from GitHub Secrets
        package: .  # Deploy the entire repository

    - name: Output Deployment URL
      run: echo "DEPLOYMENT_URL=https://${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_ENV
